# Generated by Django 2.0.6 on 2018-06-17 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import juris.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50, validators=[juris.validator.validar_rut])),
                ('tipo', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sentencia',
            fields=[
                ('id_sentencia', models.AutoField(primary_key=True, serialize=False)),
                ('juez_sentencia', models.CharField(max_length=100)),
                ('norma_aplicada', models.CharField(max_length=150)),
                ('fecha_sentencia', models.DateField()),
                ('materias_sentencia', models.CharField(max_length=100)),
                ('fecha_agregacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tribunal',
            fields=[
                ('id_tribunal', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_tribunal', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sentencia',
            name='nombre_tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.tribunal'),
        ),
    ]
